version: 1.0.0+1
name: noty_mobile
publish_to: 'none'
description: Noty application

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  navigation:
    path: navigation
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  get_it: ^7.2.0
  printing: 5.9.3
  screenshot: ^1.3.0
  easyqrimage: ^0.0.2
  flutter_bloc: ^7.3.3
  flutter_share: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  path_provider: ^2.0.0-nullsafety
  google_mlkit_text_recognition: ^0.5.0
  firebase_auth: ^4.2.5
  flutter_svg: ^1.1.1+1
  url_launcher: ^6.1.8
  qr_code_scanner: ^1.0.1
  google_sign_in: ^5.4.1
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  firebase_remote_config: ^3.0.9
  font_awesome_flutter: ^10.3.0
  step_progress_indicator: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_local_notifications: ^13.0.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/navigation/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 700